### ISSUE TITLE
对实现文件141行在枚举遍历里面使用自动释放池的疑问

### ISSUE THREAD

**Issue by jhchenchong** [CodeWicky/DWEventBus#1]
系统的enumerateObjectsUsingBlock方法在内部是有内置一个自动释放池的。请问这里这样写是有其他的用意吗？

**Comment by CodeWicky** [comment]
> 系统的enumerateObjectsUsingBlock方法在内部是有内置一个自动释放池的。请问这里这样写是有其他的用意吗？

十分感谢，没有其他用以，的确是之前忘记了系统已经提供了释放池，我会在下个版本中将此处改正。感谢你对问题的指正。

**Comment by CodeWicky** [comment]
-

**Comment by esodck** [comment]
你好，想跟您合作cp马甲包，我是彩票直客，qq。2222223863
